/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author copec
 */
public class AdministradorFrame extends javax.swing.JFrame {

    /**
     * Creates new form OperadorFrame
     */
    public AdministradorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        panelDerecha = new javax.swing.JPanel();
        equisde = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        agregarProductosPanel = new javax.swing.JPanel();
        etiquetaFormaCrearUno = new javax.swing.JLabel();
        nombreEstante = new javax.swing.JTextField();
        estanteNeim = new javax.swing.JLabel();
        cantidadEspacios = new javax.swing.JTextField();
        espaciosDelEstante = new javax.swing.JLabel();
        wardEstante = new javax.swing.JButton();
        etiquetaFormaCrearDos = new javax.swing.JLabel();
        nombreEstante2 = new javax.swing.JTextField();
        stanteNeim = new javax.swing.JLabel();
        cantidadDeEspacios = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tamanioEspacio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ampliarCatalogoPanel = new javax.swing.JPanel();
        agregarUnProducto = new javax.swing.JLabel();
        tiposDeProducto = new javax.swing.JComboBox<>();
        tipoDeProducto = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JTextField();
        precioProducto = new javax.swing.JTextField();
        fechaCaducidad = new javax.swing.JTextField();
        unidadDeMedida = new javax.swing.JTextField();
        clasifOEspecif = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        productNeim = new javax.swing.JLabel();
        productCost = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        reducirCatalogoPanel = new javax.swing.JPanel();
        listaEstantes1 = new javax.swing.JComboBox<>();
        etiquetaEstante1 = new javax.swing.JLabel();
        nombreProductoActual = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        productNeimEliminar = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        nombreProductoEliminar = new javax.swing.JTextField();
        productNeimEliminarr = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        panelIzquierda = new javax.swing.JPanel();
        agregarEstante = new javax.swing.JButton();
        ampliarCatalogo = new javax.swing.JButton();
        reducirCatalogo = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelDerecha.setPreferredSize(new java.awt.Dimension(390, 410));
        panelDerecha.setLayout(new java.awt.CardLayout());

        Welcome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Welcome.setText("Bienvenido al panel Administrador");

        javax.swing.GroupLayout equisdeLayout = new javax.swing.GroupLayout(equisde);
        equisde.setLayout(equisdeLayout);
        equisdeLayout.setHorizontalGroup(
            equisdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equisdeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Welcome)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        equisdeLayout.setVerticalGroup(
            equisdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equisdeLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        panelDerecha.add(equisde, "card2");

        agregarProductosPanel.setPreferredSize(new java.awt.Dimension(390, 410));

        etiquetaFormaCrearUno.setText("Crear estante por defecto");

        estanteNeim.setText("Nombre del estante");

        espaciosDelEstante.setText("Cantidad de espacios");

        wardEstante.setText("Guardar estante");

        etiquetaFormaCrearDos.setText("Crear estante personalizado");

        stanteNeim.setText("Nombre del estante");

        jLabel1.setText("Cantidad de espacios");

        jLabel2.setText("Tamaño de cada espacio");

        jButton1.setText("Guardar estante");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin estantes" }));

        jLabel5.setText("Estantes definidos");

        javax.swing.GroupLayout agregarProductosPanelLayout = new javax.swing.GroupLayout(agregarProductosPanel);
        agregarProductosPanel.setLayout(agregarProductosPanelLayout);
        agregarProductosPanelLayout.setHorizontalGroup(
            agregarProductosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarProductosPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(agregarProductosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tamanioEspacio)
                    .addComponent(cantidadDeEspacios)
                    .addGroup(agregarProductosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(wardEstante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cantidadEspacios)
                        .addComponent(etiquetaFormaCrearUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombreEstante))
                    .addComponent(nombreEstante2)
                    .addComponent(etiquetaFormaCrearDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(agregarProductosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(agregarProductosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(stanteNeim)
                        .addComponent(estanteNeim)
                        .addComponent(espaciosDelEstante)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        agregarProductosPanelLayout.setVerticalGroup(
            agregarProductosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarProductosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaFormaCrearUno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(agregarProductosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreEstante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estanteNeim))
                .addGap(18, 18, 18)
                .addGroup(agregarProductosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadEspacios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espaciosDelEstante))
                .addGap(18, 18, 18)
                .addComponent(wardEstante)
                .addGap(31, 31, 31)
                .addComponent(etiquetaFormaCrearDos)
                .addGap(18, 18, 18)
                .addGroup(agregarProductosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreEstante2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stanteNeim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(agregarProductosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadDeEspacios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(agregarProductosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamanioEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(agregarProductosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        panelDerecha.add(agregarProductosPanel, "card3");

        agregarUnProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        agregarUnProducto.setText("Agregar un producto al catálogo");

        tiposDeProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de producto", "Medicamento", "Material de curación" }));

        tipoDeProducto.setText("Tipo de producto");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione tamaño", "Chico", "Mediano", "Grande" }));

        productNeim.setText("Nombre del producto");

        productCost.setText("Precio del producto");

        jLabel6.setText("Fecha de caducidad");

        jLabel7.setText("Unidad de medida");

        jLabel8.setText("Clasificacion/Espeficiacion");

        jLabel9.setText("Tamaño del producto");

        jButton3.setText("Agregar al catálogo");

        javax.swing.GroupLayout ampliarCatalogoPanelLayout = new javax.swing.GroupLayout(ampliarCatalogoPanel);
        ampliarCatalogoPanel.setLayout(ampliarCatalogoPanelLayout);
        ampliarCatalogoPanelLayout.setHorizontalGroup(
            ampliarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ampliarCatalogoPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ampliarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarUnProducto)
                    .addGroup(ampliarCatalogoPanelLayout.createSequentialGroup()
                        .addGroup(ampliarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clasifOEspecif, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unidadDeMedida, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaCaducidad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precioProducto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreProducto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tiposDeProducto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(ampliarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ampliarCatalogoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addContainerGap(79, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ampliarCatalogoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ampliarCatalogoPanelLayout.createSequentialGroup()
                                .addGroup(ampliarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productCost, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productNeim, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoDeProducto, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(ampliarCatalogoPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ampliarCatalogoPanelLayout.setVerticalGroup(
            ampliarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ampliarCatalogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agregarUnProducto)
                .addGap(18, 18, 18)
                .addGroup(ampliarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiposDeProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoDeProducto))
                .addGap(18, 18, 18)
                .addGroup(ampliarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productNeim))
                .addGap(18, 18, 18)
                .addGroup(ampliarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productCost))
                .addGap(18, 18, 18)
                .addGroup(ampliarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(ampliarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidadDeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(ampliarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clasifOEspecif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(ampliarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        panelDerecha.add(ampliarCatalogoPanel, "card5");

        reducirCatalogoPanel.setPreferredSize(new java.awt.Dimension(390, 410));

        listaEstantes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Productos", " " }));

        etiquetaEstante1.setText("Producto: \"  \"");

        nombreProductoActual.setEditable(false);
        nombreProductoActual.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton2.setText("Guardar cambios");
        jButton2.setToolTipText("");

        productNeimEliminar.setText("Nombre del producto");

        jButton4.setText("Eliminar del catálogo");

        productNeimEliminarr.setText("Nombre del producto");

        jButton5.setText("Eliminar del catálogo");

        javax.swing.GroupLayout reducirCatalogoPanelLayout = new javax.swing.GroupLayout(reducirCatalogoPanel);
        reducirCatalogoPanel.setLayout(reducirCatalogoPanelLayout);
        reducirCatalogoPanelLayout.setHorizontalGroup(
            reducirCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reducirCatalogoPanelLayout.createSequentialGroup()
                .addGroup(reducirCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reducirCatalogoPanelLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(reducirCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(reducirCatalogoPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(reducirCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(reducirCatalogoPanelLayout.createSequentialGroup()
                                .addComponent(nombreProductoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(productNeimEliminarr))
                            .addGroup(reducirCatalogoPanelLayout.createSequentialGroup()
                                .addGroup(reducirCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombreProductoActual)
                                    .addComponent(listaEstantes1, 0, 125, Short.MAX_VALUE))
                                .addGap(47, 47, 47)
                                .addGroup(reducirCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaEstante1)
                                    .addComponent(productNeimEliminar))))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        reducirCatalogoPanelLayout.setVerticalGroup(
            reducirCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reducirCatalogoPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(reducirCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaEstantes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaEstante1))
                .addGap(18, 18, 18)
                .addGroup(reducirCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreProductoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productNeimEliminar))
                .addGap(26, 26, 26)
                .addComponent(jButton4)
                .addGap(26, 26, 26)
                .addGroup(reducirCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreProductoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productNeimEliminarr))
                .addGap(30, 30, 30)
                .addComponent(jButton5)
                .addGap(95, 95, 95)
                .addComponent(jButton2)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        panelDerecha.add(reducirCatalogoPanel, "card3");

        getContentPane().add(panelDerecha, java.awt.BorderLayout.EAST);

        panelIzquierda.setPreferredSize(new java.awt.Dimension(140, 40));

        agregarEstante.setText("Agregar Estante");
        agregarEstante.setToolTipText("");
        agregarEstante.setPreferredSize(new java.awt.Dimension(97, 23));
        agregarEstante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEstanteActionPerformed(evt);
            }
        });

        ampliarCatalogo.setText("Ampliar catálogo");
        ampliarCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ampliarCatalogoActionPerformed(evt);
            }
        });

        reducirCatalogo.setText("Reducir catálogo");
        reducirCatalogo.setPreferredSize(new java.awt.Dimension(97, 23));
        reducirCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reducirCatalogoActionPerformed(evt);
            }
        });

        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIzquierdaLayout = new javax.swing.GroupLayout(panelIzquierda);
        panelIzquierda.setLayout(panelIzquierdaLayout);
        panelIzquierdaLayout.setHorizontalGroup(
            panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(reducirCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregarEstante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ampliarCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelIzquierdaLayout.setVerticalGroup(
            panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdaLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(agregarEstante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(ampliarCatalogo)
                .addGap(32, 32, 32)
                .addComponent(reducirCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarSesion)
                .addGap(53, 53, 53))
        );

        getContentPane().add(panelIzquierda, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarEstanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEstanteActionPerformed
        panelDerecha.removeAll();
        panelDerecha.repaint();
        panelDerecha.revalidate();
        panelDerecha.add(agregarProductosPanel);
        panelDerecha.repaint();
        panelDerecha.revalidate();
    }//GEN-LAST:event_agregarEstanteActionPerformed

    private void reducirCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reducirCatalogoActionPerformed
        panelDerecha.removeAll();
        panelDerecha.repaint();
        panelDerecha.revalidate();
        panelDerecha.add(reducirCatalogoPanel);
        panelDerecha.repaint();
        panelDerecha.revalidate();
    }//GEN-LAST:event_reducirCatalogoActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
                int result = JOptionPane.showConfirmDialog(null, "Esta seguro?", "InfoBox: " + "confirmar", JOptionPane.OK_CANCEL_OPTION);
       if(result == JOptionPane.OK_OPTION){
       MainFrame mf = new MainFrame();
       this.dispose();
       mf.setVisible(true);
       }
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void ampliarCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ampliarCatalogoActionPerformed
panelDerecha.removeAll();
        panelDerecha.repaint();
        panelDerecha.revalidate();
        panelDerecha.add(ampliarCatalogoPanel);
        panelDerecha.repaint();
        panelDerecha.revalidate();
    }//GEN-LAST:event_ampliarCatalogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Welcome;
    private javax.swing.JButton agregarEstante;
    private javax.swing.JPanel agregarProductosPanel;
    private javax.swing.JLabel agregarUnProducto;
    private javax.swing.JButton ampliarCatalogo;
    private javax.swing.JPanel ampliarCatalogoPanel;
    private javax.swing.JTextField cantidadDeEspacios;
    private javax.swing.JTextField cantidadEspacios;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JTextField clasifOEspecif;
    private javax.swing.JPanel equisde;
    private javax.swing.JLabel espaciosDelEstante;
    private javax.swing.JLabel estanteNeim;
    private javax.swing.JLabel etiquetaEstante1;
    private javax.swing.JLabel etiquetaFormaCrearDos;
    private javax.swing.JLabel etiquetaFormaCrearUno;
    private javax.swing.JTextField fechaCaducidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> listaEstantes1;
    private javax.swing.JTextField nombreEstante;
    private javax.swing.JTextField nombreEstante2;
    private javax.swing.JTextField nombreProducto;
    private javax.swing.JTextField nombreProductoActual;
    private javax.swing.JTextField nombreProductoEliminar;
    private javax.swing.JPanel panelDerecha;
    private javax.swing.JPanel panelIzquierda;
    private javax.swing.JTextField precioProducto;
    private javax.swing.JLabel productCost;
    private javax.swing.JLabel productNeim;
    private javax.swing.JLabel productNeimEliminar;
    private javax.swing.JLabel productNeimEliminarr;
    private javax.swing.JButton reducirCatalogo;
    private javax.swing.JPanel reducirCatalogoPanel;
    private javax.swing.JLabel stanteNeim;
    private javax.swing.JTextField tamanioEspacio;
    private javax.swing.JLabel tipoDeProducto;
    private javax.swing.JComboBox<String> tiposDeProducto;
    private javax.swing.JTextField unidadDeMedida;
    private javax.swing.JButton wardEstante;
    // End of variables declaration//GEN-END:variables
}
